# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'axaguildev'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'skizzle'
    cliProjectName: 'skizzle'
    cliProjectVersion: '1.0.1'
    cliSources: 'src'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.tests=src
      sonar.test.inclusions=src/**/*.test.js
      sonar.javascript.lcov.reportPaths=coverage/lcov.info

- script: npm install && npm run bootstrap
  displayName: 'npm install and bootstrap'

- script: npm test -- --coverage
  displayName: 'npm run test:coverage'
